### ISSUE TITLE
Ellenőrzés

### ISSUE THREAD

**Issue by mate09305** [PE-MK-JAKI-H/AHTGEK#3]
Tisztelt Tanár Úr!

Feltöltöttem commitba a végleges verziómat amelyet ellőrzésre szeretnék bocsájtani.

Köszönettel,

Palumbéli Máté

**Comment by Szalay** [comment]
Átnézem, a következők az észrevételeim:
1) Kimaradt a commitból a gyökérdokumentum és a lefordított PDF.
2) Korábban azt írtad, hogy Visioban rajzolnál, ha ez megtörtént már, akkor azok az ábrák is kimaradtak.
3) Az első és a harmadik ábra elfogadható, a második viszont, hát, nem olyan szép :)
4) Az átmérő jele `\diameter`. Ez olyan sokszor előfordul, hogy felírom. Az áthúzott 0 nem átmérőjel, a fí sem az és a nagy fí sem az.
5) A mennyiségek betűjelei a szövegben sorközi egyenletek legyenek!
6) A szabványfordítás rendben van, csak kisebb szekesztési hibák vannak. Az upsteam/downstream itt lehet beömlő/kiömlő oldal.

A kettőtök munkát egyesíteni kellene, és feltölteni a feladat teljes megoldását mindkettőtök ágára.

**Comment by mate09305** [comment]
Tisztelt Tanár Úr!

Elvégeztem a kért változtatáskat, remélem a sorközi egyenletek esetében jól értelmeztem a feladatot.

Végül elvetettem a Visio-s ötletet, mivel Ön sem kért több ábrát a szabványból, valamint a méréstechnikást részből más már nem maradt nekem az órai anyagból. A második ábrát illetően szeretném segítségét kérni, hogy min lenne szükséges még változtatni/javítani.

Olvastam a Letíciával folytatott egyeztetést. Mivel én zárvizsgázok ebben a félévben, a jövő hét folyamán legkésőbb szeretnék abszolválni, így ha az elkészített dokumentum eléri az elégséges szintet, megelégednék ezzel az eredménnyel.

Előre is köszönöm segítségét.

Tisztelettel,

Palumbéli Máté

**Comment by Szalay** [comment]
Lezártam az issue-t, mert már tátgytalan.
