### ISSUE TITLE
Ellenőrzés KSE6SY

### ISSUE THREAD

**Issue by Szalay** [PE-MK-JAKI-H/AHTGEK#4]
Kellet volna nyitni egy új issue-t a feltöltés után.

**Comment by Szalay** [comment]
Átnéztem a feltöltött anyagot, és sajnos vannak vele problémák. Vázlatosan leírtad az első fejezetet, ami nem volt része a feladatnak, de szerencsére azért nem volt értelmetlen, és be tudom számítani az eredménybe. Hibák vannak benne.

A második feladat felépítése végülis jó, de túlzottan vázlatos. A mérőműszerek mindegyikénél lehetne egy-egy épkézláb, összefüggő mondatot foglamazni. 

Kisebb szerkesztési hibákból elég sok van:
1)  fölösleges szorzásjelek az egyenletekben,
2) a sűrűséget `\varrho`-val szokás jelölni
3) Toricelli, Venturi
4) Tömeg vektor!?
5) `\pm` a ±

A fentiek javításával az elégésges szintet eléri a beadandó, de ha ennél többet nem szeretnél javítani, akkor is egyesíteni kell a beadandót a Palumbéli Máté ábráival.

**Comment by somlail** [comment]
Tisztelt Tanár úr!

Javítani fogom a hibáimat, valamint kiegészítem a rajzokkal is, csak még
nem volt rá időm. Elvileg nekem az utolsó vizsga napjáig van időm a
leadásra, mivel vizsgakurzusos vagyok. Meg szeretném kérdezni, hogy a Máté,
az én anyagom nélkül is megkaphatja a jegyét, és azt hogy ha én később adom
le, az nem rontja az ő jegyét? Valamint megmagyarázná azt, hogy mi az az
issue amiről nemrég emailt küldött és hol kellene azt létrehoznom?

Válaszát előre is köszönöm!

Tisztelettel Somlai Letícia

Szalay <notifications@github.com> ezt írta (időpont: 2020. máj. 15., P
17:06):

**Comment by Szalay** [comment]
A GitHubon amolyan "ügy", vagy "kérdés" értelemben használatos szó az issue. A szóban forgót itt találod: https://github.com/PE-MK-JAKI-H/AHTGEK/issues/4

Kettébontható a feladat, ha meg tudunk egyezni a felosztás módjában/arányában. A határidő az utolsó vizsgaalkalom előtti nap, így ha  valakinek nem elfogadható a beadandója, akkor elvi szinten még marad javítási lehetősége.

**Comment by somlail** [comment]
Tisztelt Tanár úr!

Meg szeretném Öntől kérdezni, hogy az egyenletekbe milyen módon tudok hosszú ékezetes magánhangzókat alkalmazni? Emelett az ábrázolós résznél írta a moodleban, hogy az Ön forrásából ki kell másolni valamit, ahhoz, hogy pl. az utak vonalkázását meg tudjam oldani. Mit is kellene pontosan, mert nem sikerült rájönnöm?

A nem rég feltöltött frissítésem még nem a kész verzió, az Ön által írt hibák egy részét tudtam még csak kijavítani, még javítás alatt áll a többi része.

Válaszát és segítségét előre is köszönöm!

Tisztelettel Somlai Letícia

**Comment by Szalay** [comment]
Az egyenletekben szigorúan véve nem tudsz ékezetes betűt tenni, viszont tudsz szöveget tenni az egyenletekbe. Ezt kell kihasználni. A szükséges parancsok a \text{} és a \textit. Például: `v_{\textit{átl}}`, `A_{\textit{Ö}}`, vagy `a = 1 \quad \text{és} \quad b = 2`

**Comment by Szalay** [comment]
Ahhoz, hogy a vonalkázást meg tudd csinálni, a mester ágat a sajátodba kell fésülni, mert utólag adtam csak hozzá a vonalkázó könyvtárat a sablonhoz. A következő lépéseket kell végigcsinálni:

(1) A saját gépeden minden változást commitolni, és csinálni egy push origint.

(2) 
![image](https://user-images.githubusercontent.com/8204804/83355499-1dc72600-a360-11ea-957a-d083504fa7fb.png)

(3) 
![image](https://user-images.githubusercontent.com/8204804/83355770-c75ae700-a361-11ea-9384-2a827d1ee3ca.png)

(4)
![image](https://user-images.githubusercontent.com/8204804/83355810-038e4780-a362-11ea-9ee2-685e1fcd33e7.png)

(5) Ellenőrizni, hogy a GitHub Desktop letöltötte-e a frissített fájlokat. Ezt gyorsan meg tudod tenni, ha megnézed a JakiTikz.texben a 6. sort, ahol ott kell legyen a patterns.meta
![image](https://user-images.githubusercontent.com/8204804/83355959-0b022080-a363-11ea-8f31-d5afa1169e67.png)

**Comment by somlail** [comment]
Tisztelt Tanár úr!

Köszönöm szépen az előző részletes segítséget!
Feltöltöttem a javításomat. Írta, hogy az egyenletekben felesleges szórzásjelek vannak. Esetleg meg tudná mondani, hogy melyikekből kellene kivennem? Illetve átnézné, hogy van-e olyan hibám amit még javítanom kellene, vagy így már elfogadható?

Válaszát és segítségét előre is köszönöm!

Tisztelettel Somlai Letícia

**Comment by somlail** [comment]
Tisztelt Tanár úr!

Köszönöm szépen az előző részletes segítséget!
Feltöltöttem a javításomat. Írta, hogy az egyenletekben felesleges szórzásjelek vannak. Esetleg meg tudná mondani, hogy melyikekből kellene kivennem? Illetve átnézné, hogy van-e olyan hibám amit még javítanom kellene, vagy így már elfogadható?

Válaszát és segítségét előre is köszönöm!

**Comment by Szalay** [comment]
Átnéztem és pontoztam a jelenlegi állapot alapján, az eredményt megtalálod a Google-táblázatban.

Ha szeretnél még javítani a beadandón, akkor írok egy listát a hibákról.

**Comment by somlail** [comment]
Tisztelt Tanár úr!

Szeretnék még javítani rajta, várom az észrevételeit.

**Comment by Szalay** [comment]
Két területen lehetne javítani, mindegyikkel elérhető az ötös szint:
1) Az elméleti részeken szöveges magyarázatokat kellene fogalmazni az egyenletek mellé, leírni a mennyiségek és az egyenletek jelentését.
2) Az ábrákon lehetne sokat javítani.

**Comment by somlail** [comment]
Tisztelt Tanár úr!

Esetleg azt is meg lehetne csinálni pontszerzés érdekben, hogy az egyik 25 pontos feladatot most még megcsinálnám? Mert a gőz-gáz turbina összehasonlításos részt szívesen elválalnám. 
Ha ez még elfogadható opció megkérdezhetném azt, hogy az órán vett táblázaton és példák gyűjtésén kívül, esetleg kellene valami mást is csinálnom rajta, kell hozzá ábra vagy elég a táblázat meg a példák?

Válaszát előre is köszönöm!

**Comment by somlail** [comment]
Tisztelt Tanár úr!

Megcsináltam a gőz-gáz turbinás (25 pontos) feladatot is, és javítottam az eredeti egyes részeit. Ha ideje engedi, legyen szíves átnézni.

**Comment by Szalay** [comment]
Átnéztem újra és frissítettem a pontozást, az eredményt megtalálod a Google-táblázatban.

A vizsgára jelentkezz, ha még nem tetted meg!
