### ISSUE TITLE
AHTGEK 2. fejezet

### ISSUE THREAD

**Issue by peti3486** [PE-MK-JAKI-H/AHTGEK#6]
Tisztelt Tanár Úr!

A feladatomnak én az ÁHTGEK kidolgozások közül a 2. feladatot választottam. Itt a leírás szerint a 2. fejezetet és a kérdéssor 3-8. kérdésig terjedő szakaszát kell kidolgoznom.
Viszont ezek a kérdések lefedik teljesen a 2. fejezetnek az órán a füzetbe jegyzetelt részét.
Elegendő csupán a kérdéseket így kidolgozni? Ha nem, akkor még mit tudnék a fejezethez írni?

Illetve még azt szeretném kérdezni, hogy a jegy beírása miatt szükséges-e vizsgát felvenni akkor is, ha beadandóval szeretném a tárgyat teljesíteni?

Válaszát köszönöm előre is!

**Comment by Szalay** [comment]
A vizsgára jeletkezned kell, és vizsgajegyként tudom megadni a beadandóval elért jegyet.

Azért adtam meg a 2. fejezetet és a kérdések számait is, hogy egyértelműbb legyen, mi tartozik hozzá a feladathoz. A beadandó felépítése viszont inkább a 2. fejezet felépítését kövesse, és a kérdéssor kérdései a megfelelő helyen ezen belül legyenek megválaszolva! Tartalmilag ezen felül nem kell kiegészíteni, inkább az ábrákra fordíts több figyelmet!

**Comment by peti3486** [comment]
Tisztelt Tanár Úr!

Elkészültem a feladatommal, szeretnék kérni egy ellenőrzést és amennyiben megfelel a beadandóm érdeklődni szeretnék a végleges leadás módjáról és a további teendőimről.
Válaszát és segítségét előre is köszönöm!

Tisztelettel:
György Péter

**Comment by Szalay** [comment]
Átnéztem és pontoztam, az eredményt megtalálod a Google-táblázatban. Nem tökéletes, de mivel a jegyen nem változtat, ezért nem javíttatom ki a hibákat. Egyet, a leggyakoribbat azért megemlítem: a vektoroknál a nyílnak nem szabadna az alsóindex fölé lógni. Így csináltad: `$\vec{c_1}$`, és így kellett volna: `$\vec{c}_1$`.

Vizsgára kell még jelentkezned, de ezen kívül más teendőd nincs. Pull request nem kell,
